### ISSUE TITLE
Example for DynamoDB

### ISSUE THREAD

**Issue by jetzlstorfer** [viant/dsc#8]
Hi, 
could you please provide an example how to use DynamoDB or at least how to connection string for DynamoDB has to look like?
Thanks!

**Comment by adranwit** [comment]
Good call, I will add dbynamo db example.

Besides the driver name, you have to supply the following parameters
- key - AWS key
- secret - AWS secret
- region - AWS region
- dbname


https://github.com/adrianwit/dyndb/blob/master/connection.go


Here is e2etesting example from
https://github.com/adrianwit/serverless_e2e/tree/master/lambda

    config:
      driverName: dyndb
      credentials: $awsCredentials
    tables:
      - table: Events
        pkColumns:
          - Date
          - EventType
        schemaURL: ${parent.path}/db1/schema/events.json

Where schema looks like the following:

{
  "AttributeDefinitions": [
    {
      "AttributeName": "EventDate",
      "AttributeType": "S"
    },
    {
      "AttributeName": "EventType",
      "AttributeType": "N"
    }

  ],
  "KeySchema": [
    {
      "AttributeName": "EventDate",
      "KeyType": "HASH"
    },
    {
      "AttributeName": "EventType",
      "KeyType": "RANGE"
    }
  ],
  "ProvisionedThroughput": {
    "ReadCapacityUnits": 1,
    "WriteCapacityUnits": 1
  }
}

**Comment by adranwit** [comment]
Updated doc: https://github.com/viant/dsc/tree/master/docs
Looks like I've already added an example to dsunit 
https://github.com/viant/dsunit/tree/master/example/dynamodb

**Comment by jetzlstorfer** [comment]
Great, thanks!
